
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: May  5 2026 06:05:59 EDT (May  5 2026 10:05:59 UTC)

// Verification Directory fv/Techboys_4bit 

module Techboys_4bit(clk, reset, write_en, w_addr, w_data, r_addr1,
     r_addr2, r_data1, r_data2);
  input clk, reset, write_en;
  input [1:0] w_addr, r_addr1, r_addr2;
  input [3:0] w_data;
  output [3:0] r_data1, r_data2;
  wire clk, reset, write_en;
  wire [1:0] w_addr, r_addr1, r_addr2;
  wire [3:0] w_data;
  wire [3:0] r_data1, r_data2;
  wire [3:0] \reg_array[0] ;
  wire [3:0] \reg_array[1] ;
  wire [3:0] \reg_array[2] ;
  wire [3:0] \reg_array[3] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_34, n_35, n_36, n_37, n_38;
  SDFFRHQX1 \reg_array_reg[0][0] (.RN (n_38), .CK (clk), .D
       (\reg_array[0] [0]), .SI (w_data[0]), .SE (n_35), .Q
       (\reg_array[0] [0]));
  SDFFRHQX1 \reg_array_reg[1][3] (.RN (n_38), .CK (clk), .D
       (w_data[3]), .SI (\reg_array[1] [3]), .SE (n_34), .Q
       (\reg_array[1] [3]));
  SDFFRHQX1 \reg_array_reg[2][0] (.RN (n_38), .CK (clk), .D
       (\reg_array[2] [0]), .SI (w_data[0]), .SE (n_37), .Q
       (\reg_array[2] [0]));
  SDFFRHQX1 \reg_array_reg[2][1] (.RN (n_38), .CK (clk), .D
       (\reg_array[2] [1]), .SI (w_data[1]), .SE (n_37), .Q
       (\reg_array[2] [1]));
  SDFFRHQX1 \reg_array_reg[2][2] (.RN (n_38), .CK (clk), .D
       (\reg_array[2] [2]), .SI (w_data[2]), .SE (n_37), .Q
       (\reg_array[2] [2]));
  SDFFRHQX1 \reg_array_reg[2][3] (.RN (n_38), .CK (clk), .D
       (\reg_array[2] [3]), .SI (w_data[3]), .SE (n_37), .Q
       (\reg_array[2] [3]));
  SDFFRHQX1 \reg_array_reg[3][0] (.RN (n_38), .CK (clk), .D
       (w_data[0]), .SI (\reg_array[3] [0]), .SE (n_36), .Q
       (\reg_array[3] [0]));
  SDFFRHQX1 \reg_array_reg[3][1] (.RN (n_38), .CK (clk), .D
       (w_data[1]), .SI (\reg_array[3] [1]), .SE (n_36), .Q
       (\reg_array[3] [1]));
  SDFFRHQX1 \reg_array_reg[3][2] (.RN (n_38), .CK (clk), .D
       (w_data[2]), .SI (\reg_array[3] [2]), .SE (n_36), .Q
       (\reg_array[3] [2]));
  SDFFRHQX1 \reg_array_reg[3][3] (.RN (n_38), .CK (clk), .D
       (w_data[3]), .SI (\reg_array[3] [3]), .SE (n_36), .Q
       (\reg_array[3] [3]));
  SDFFRHQX1 \reg_array_reg[0][1] (.RN (n_38), .CK (clk), .D
       (\reg_array[0] [1]), .SI (w_data[1]), .SE (n_35), .Q
       (\reg_array[0] [1]));
  SDFFRHQX1 \reg_array_reg[0][2] (.RN (n_38), .CK (clk), .D
       (\reg_array[0] [2]), .SI (w_data[2]), .SE (n_35), .Q
       (\reg_array[0] [2]));
  SDFFRHQX1 \reg_array_reg[0][3] (.RN (n_38), .CK (clk), .D
       (\reg_array[0] [3]), .SI (w_data[3]), .SE (n_35), .Q
       (\reg_array[0] [3]));
  SDFFRHQX1 \reg_array_reg[1][0] (.RN (n_38), .CK (clk), .D
       (w_data[0]), .SI (\reg_array[1] [0]), .SE (n_34), .Q
       (\reg_array[1] [0]));
  SDFFRHQX1 \reg_array_reg[1][1] (.RN (n_38), .CK (clk), .D
       (w_data[1]), .SI (\reg_array[1] [1]), .SE (n_34), .Q
       (\reg_array[1] [1]));
  SDFFRHQX1 \reg_array_reg[1][2] (.RN (n_38), .CK (clk), .D
       (w_data[2]), .SI (\reg_array[1] [2]), .SE (n_34), .Q
       (\reg_array[1] [2]));
  NAND2XL g1037__2398(.A (n_5), .B (n_15), .Y (r_data1[3]));
  NAND2XL g1040__5107(.A (n_14), .B (n_10), .Y (r_data1[1]));
  NAND2XL g1034__6260(.A (n_21), .B (n_6), .Y (r_data2[1]));
  NAND2XL g1033__4319(.A (n_13), .B (n_18), .Y (r_data1[2]));
  NAND2XL g1035__8428(.A (n_25), .B (n_9), .Y (r_data2[2]));
  NAND2XL g1038__5526(.A (n_4), .B (n_20), .Y (r_data2[3]));
  NAND2XL g1039__6783(.A (n_3), .B (n_19), .Y (r_data1[0]));
  NAND2XL g1036__3680(.A (n_24), .B (n_2), .Y (r_data2[0]));
  AOI22XL g1042__1617(.A0 (\reg_array[2] [2]), .A1 (n_23), .B0
       (\reg_array[3] [2]), .B1 (n_22), .Y (n_25));
  AOI22XL g1053__2802(.A0 (\reg_array[2] [0]), .A1 (n_23), .B0
       (\reg_array[3] [0]), .B1 (n_22), .Y (n_24));
  AOI22XL g1041__1705(.A0 (\reg_array[2] [1]), .A1 (n_23), .B0
       (\reg_array[3] [1]), .B1 (n_22), .Y (n_21));
  AOI22XL g1054__5122(.A0 (\reg_array[0] [3]), .A1 (n_8), .B0
       (\reg_array[1] [3]), .B1 (n_7), .Y (n_20));
  AOI22XL g1052__8246(.A0 (\reg_array[0] [0]), .A1 (n_17), .B0
       (\reg_array[3] [0]), .B1 (n_16), .Y (n_19));
  AOI22XL g1055__7098(.A0 (\reg_array[0] [2]), .A1 (n_17), .B0
       (\reg_array[3] [2]), .B1 (n_16), .Y (n_18));
  AOI22XL g1043__6131(.A0 (\reg_array[0] [3]), .A1 (n_17), .B0
       (\reg_array[3] [3]), .B1 (n_16), .Y (n_15));
  AOI22XL g1056__1881(.A0 (\reg_array[2] [1]), .A1 (n_12), .B0
       (\reg_array[1] [1]), .B1 (n_11), .Y (n_14));
  AOI22XL g1048__5115(.A0 (\reg_array[2] [2]), .A1 (n_12), .B0
       (\reg_array[1] [2]), .B1 (n_11), .Y (n_13));
  AOI22XL g1045__7482(.A0 (\reg_array[0] [1]), .A1 (n_17), .B0
       (\reg_array[3] [1]), .B1 (n_16), .Y (n_10));
  AOI22XL g1046__4733(.A0 (\reg_array[0] [2]), .A1 (n_8), .B0
       (\reg_array[1] [2]), .B1 (n_7), .Y (n_9));
  AOI22XL g1047__6161(.A0 (\reg_array[0] [1]), .A1 (n_8), .B0
       (\reg_array[1] [1]), .B1 (n_7), .Y (n_6));
  AOI22XL g1044__9315(.A0 (\reg_array[2] [3]), .A1 (n_12), .B0
       (\reg_array[1] [3]), .B1 (n_11), .Y (n_5));
  AOI22XL g1049__9945(.A0 (\reg_array[2] [3]), .A1 (n_23), .B0
       (\reg_array[3] [3]), .B1 (n_22), .Y (n_4));
  AOI22XL g1050__2883(.A0 (\reg_array[2] [0]), .A1 (n_12), .B0
       (\reg_array[1] [0]), .B1 (n_11), .Y (n_3));
  AOI22XL g1051__2346(.A0 (\reg_array[0] [0]), .A1 (n_8), .B0
       (\reg_array[1] [0]), .B1 (n_7), .Y (n_2));
  NOR2XL g1057__1666(.A (w_addr[0]), .B (n_0), .Y (n_37));
  NAND2XL g1058__7410(.A (w_addr[0]), .B (n_1), .Y (n_34));
  NOR2BXL g1059__6417(.AN (n_1), .B (w_addr[0]), .Y (n_35));
  NAND2BXL g1060__5477(.AN (n_0), .B (w_addr[0]), .Y (n_36));
  NAND2XL g1061__2398(.A (w_addr[1]), .B (write_en), .Y (n_0));
  NOR2BXL g1062__5107(.AN (r_addr2[0]), .B (r_addr2[1]), .Y (n_7));
  AND2X1 g1063__6260(.A (r_addr1[0]), .B (r_addr1[1]), .Y (n_16));
  NOR2XL g1064__4319(.A (r_addr1[0]), .B (r_addr1[1]), .Y (n_17));
  NOR2BXL g1065__8428(.AN (r_addr2[1]), .B (r_addr2[0]), .Y (n_23));
  NOR2BXL g1066__5526(.AN (write_en), .B (w_addr[1]), .Y (n_1));
  NOR2BXL g1067__6783(.AN (r_addr1[0]), .B (r_addr1[1]), .Y (n_11));
  NOR2XL g1068__3680(.A (r_addr2[0]), .B (r_addr2[1]), .Y (n_8));
  NOR2BXL g1069__1617(.AN (r_addr1[1]), .B (r_addr1[0]), .Y (n_12));
  AND2X1 g1070__2802(.A (r_addr2[0]), .B (r_addr2[1]), .Y (n_22));
  INVXL g1071(.A (reset), .Y (n_38));
endmodule

